### ISSUE TITLE
ion-menu in child-page is not working

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-v3#1018] opened 2019-05-01 06:51 UTC
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
After toggling to different menu, then child menu is not showing in header bar

**Expected behavior:**
it should show icon with toggle menu

**Steps to reproduce:**

**Related code:**

https://stackblitz.com/edit/ionic-6dqqpp?file=pages%2Fhome%2Fhome.ts

https://www.youtube.com/watch?v=P4-plTzkEcY&feature=youtu.be

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
{
  "name": "ionic-6dqqpp",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "rxjs": "5.4.0",
    "core-js": "2.4.1",
    "zone.js": "0.8.12",
    "typescript": "2.3.4",
    "@angular/core": "5.2.9",
    "@angular/http": "4.1.3",
    "ionic-angular": "3.9.2",
    "@angular/forms": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9"
  }
}
```

**Comment by longgt** [comment] 2019-05-02 02:32
Maybe duplicate of #816 

You can try to switch to `ion-toolbar` instead of `ion-navbar` and do workaround as described in 
https://github.com/ionic-team/ionic/issues/13496#issuecomment-346913255

**Comment by indraraj26** [comment] 2019-05-02 05:21
Dear @longgt , 

I tried as per thread, But it is not working as expected.

Open About page then open menu then don't dismiss the page, navigate to contact tab then open menu, then again hit the home tab and click on menu as about page is stack on home tab. do it this for few times you will see menu will not open for one of the page.


I have replaced navbar with toolbar and also added ionViewWillEnter & IonViewWillLeave to enable/disable menu.

Here is the playground: https://stackblitz.com/edit/ionic-6dqqpp?file=pages%2Fabout%2Fabout.ts

Thank you.

**Comment by longgt** [comment] 2019-05-02 08:44
@indraraj26 You should add the menu id as second parameter of MenuController.enable

about.ts

```
    ionViewWillLeave() {
      console.log("about leave called")
     this.menuCtrl.enable(false, 'filterMenu');
  }  
   
   ionViewWillEnter() {
      console.log("about enter called")
     this.menuCtrl.enable(true, 'filterMenu');
   }
```

contact.ts

```
    ionViewWillLeave() {
      console.log("contact leave called")
     this.menuCtrl.enable(false, 'barMenu');
  }  
   
   ionViewWillEnter() {
      console.log("contact enter called")
     this.menuCtrl.enable(true, 'barMenu');
   }
```

**Comment by indraraj26** [comment] 2019-05-02 13:29
Thank you @longgt it works as expected.

**Closed** 2019-05-08 06:35 UTC
Labels: triage

**Comment by RoroTiti** [comment] 2019-08-28 13:54
While working perfectly to solve the multi menus on same side, this solution is breaking split panel... Any progress on the topic ?
