### ISSUE TITLE
Scrolling cause freeze of App on iOS 12

### ISSUE THREAD

**Issue by filippodicostanzo** [ionic-team/ionic-v3#1003] opened 2019-04-04 21:01 UTC
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**Current behavior:**
Before an update of IOS 12.2 i don't have any issue. After the last iOS update when i choose a page from side menu the app is freeze and the scroll doesn't work. I can scroll only if there is an CSS update like turn the device orientation from portrait to landscape and the other way around.

I've tried on my 3 app develop with ionic 3.9.2

I read other discussion and i try to apply the recommended patch but didn't work.

**Expected behavior:**
Scrolling should work appropriately when navigating from side menu to page.

**Steps to reproduce:**
Important Note: I running the app on iOS 12.2

ionic cordova platform add ios
ionic cordova build ios
Open Xcode and run the app on your device
After loading when i open the sidemenu and go to other page the scrolling doesn't work

**Other information:**
Issue is specific to iOS; does not affect Android

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.4-201903121725
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 5.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 14 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 7.0.0
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```

**Comment by maerlynflagg** [comment] 2019-04-10 07:21
My issue is similar this.  after updating to iOS 12.2 i can't scroll in a new opened modal.

but after changing the orientation to landscape and back to portrait, scrolling is working.

**Comment by filippodicostanzo** [comment] 2019-04-10 08:09
Try to update the new version of ionic angular with npm
`npm i ionic-angular@nightly
`

**Comment by JoeMeeks** [comment] 2019-04-16 16:45
Just add this to your scss:
```
ion-app.platform-ios12 ion-content { pointer-events: auto; /*fix scroll lock on ios12.2*/ }
```

**Comment by liamdebeasi** [comment] 2019-04-16 18:24
Hi there,

I am going to close this as a duplicate of https://github.com/ionic-team/ionic-v3/issues/1004.

Thanks!

**Closed by liamdebeasi** 2019-04-16 18:24 UTC
Labels: triage

**Comment by rafaelzmt** [comment] 2019-06-25 23:08
> Just add this to your scss:
> 
> ```
> ion-app.platform-ios12 ion-content { pointer-events: auto; /*fix scroll lock on ios12.2*/ }
> ```

Works for me, tks

**Comment by rhafiko** [comment] 2019-09-26 13:17
> Just add this to your scss:
> 
> ```
> ion-app.platform-ios12 ion-content { pointer-events: auto; /*fix scroll lock on ios12.2*/ }
> ```

works for me. thank you.

**Comment by YaroslavG** [comment] 2019-10-03 08:08
the problem is still on ios 12.3.1

**Comment by Bkhadija** [comment] 2019-10-18 14:01
@YaroslavG yes the problem is still on ios 12.3.1.
Any other workaround guys ?  setting "pointer-events: auto" is not working for me so as the other solutions :(

**Comment by YabinSong** [comment] 2019-10-31 14:47
@YaroslavG  @Bkhadija  I'm also still having the problem. Did you find any solution?

**Comment by Bkhadija** [comment] 2019-10-31 15:03
@YabinSong check the last comments in here https://github.com/ionic-team/ionic-v3/issues/984
